/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_05_cumpleanios_feliz;

import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class CumpleaniosFelizSpinner extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CumpleaniosFelizSpinner.class.getName());

    /**
     * Creates new form CumpleaniosFeliz
     */
    public CumpleaniosFelizSpinner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFechaNac = new javax.swing.JLabel();
        jSpinnerFechaNac = new javax.swing.JSpinner();
        jButtonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFechaNac.setText(org.openide.util.NbBundle.getMessage(CumpleaniosFelizSpinner.class, "CumpleaniosFelizSpinner.jLabelFechaNac.text")); // NOI18N

        jSpinnerFechaNac.setModel(new javax.swing.SpinnerDateModel());

        jButtonCalcular.setText(org.openide.util.NbBundle.getMessage(CumpleaniosFelizSpinner.class, "CumpleaniosFelizSpinner.jButtonCalcular.text")); // NOI18N
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelFechaNac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButtonCalcular)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelFechaNac)
                    .addComponent(jSpinnerFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButtonCalcular)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        Date dateNac = (Date) jSpinnerFechaNac.getValue();

        // Convertimos Date a LocalDate
        LocalDate fechaNac = dateNac.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        LocalDate hoy = LocalDate.now();

        // Cálculos para siguiente cumple
        int diaNacimiento = fechaNac.getDayOfMonth();
        int mesNacimiento = fechaNac.getMonthValue();

        LocalDate proxCumple = LocalDate.of(hoy.getYear(), mesNacimiento, diaNacimiento);

        // Si el cumpleaños ya pasó sumamos 1 año
        if (proxCumple.isBefore(hoy) || proxCumple.isEqual(hoy)) {
            proxCumple = proxCumple.plusYears(1);
        }

        // Con ChronoUnit y between obtenemos la diferencia de años de manera precisa
        int edad = (int) ChronoUnit.YEARS.between(fechaNac, hoy);

        // Calcula los días para el prox cumpleaños
        long diasParaCumple = ChronoUnit.DAYS.between(hoy, proxCumple);

        JOptionPane.showMessageDialog(this, "Tienes " + edad + " años y quedan " + diasParaCumple 
                + " días para tu siguiente cumple", "CUMPLEAÑOS", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButtonCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CumpleaniosFelizSpinner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JSpinner jSpinnerFechaNac;
    // End of variables declaration//GEN-END:variables
}
