/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_06_fecha_aleatoria;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class FechaAleatoria extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FechaAleatoria.class.getName());

    /**
     * Creates new form FechaAleatoria
     */
    public FechaAleatoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFechaAleatoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonFechaAleatoria.setBackground(new java.awt.Color(0, 153, 153));
        jButtonFechaAleatoria.setText(org.openide.util.NbBundle.getMessage(FechaAleatoria.class, "FechaAleatoria.jButtonFechaAleatoria.text")); // NOI18N
        jButtonFechaAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFechaAleatoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButtonFechaAleatoria)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButtonFechaAleatoria)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFechaAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFechaAleatoriaActionPerformed
        // Año actual
        int anioActual = LocalDate.now().getYear();

        // Definimos inico y fin del año
        LocalDate inicioAnio = LocalDate.of(anioActual, 1, 1);
        LocalDate finAnio = LocalDate.of(anioActual, 12, 31);

        // Calculamos el nº total de dias, sumamos +1 para incluir el 1 de enero y 31 de diciembre
        long diasTotales = ChronoUnit.DAYS.between(inicioAnio, finAnio) + 1;

        // Seleccionamos un dia aleatorio en ese rango de días
        Random random = new Random();

        long diasAleatorios = random.nextInt((int) diasTotales);

        // Le sumamos esos días al inicio del año y nos devuelve una fecha
        LocalDate fechaAleatoria = inicioAnio.plusDays(diasAleatorios);

        JOptionPane.showMessageDialog(this, "Fecha: " + fechaAleatoria + ", y el día de la semana es: " + fechaAleatoria.getDayOfWeek(), "Fecha aleatoria", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_jButtonFechaAleatoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FechaAleatoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechaAleatoria;
    // End of variables declaration//GEN-END:variables
}
