/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_15_panel_tematico;

/**
 *
 * @author Robert
 */
public class PanelTematico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelTematico.class.getName());

    /**
     * Creates new form PanelTematico
     */
    public PanelTematico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(PanelTematico.class, "PanelTematico.jLabel1.text")); // NOI18N
        jPanel.add(jLabel1);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setText(org.openide.util.NbBundle.getMessage(PanelTematico.class, "PanelTematico.jButton1.text")); // NOI18N
        jPanel.add(jButton1);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PanelTematico.class, "PanelTematico.jLabel2.text")); // NOI18N
        jPanel.add(jLabel2);

        jButton2.setBackground(new java.awt.Color(204, 204, 0));
        jButton2.setText(org.openide.util.NbBundle.getMessage(PanelTematico.class, "PanelTematico.jButton2.text")); // NOI18N
        jPanel.add(jButton2);

        jButton3.setBackground(new java.awt.Color(0, 153, 51));
        jButton3.setText(org.openide.util.NbBundle.getMessage(PanelTematico.class, "PanelTematico.jButton3.text")); // NOI18N
        jPanel.add(jButton3);

        jLabel3.setBackground(new java.awt.Color(0, 255, 204));
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setText(org.openide.util.NbBundle.getMessage(PanelTematico.class, "PanelTematico.jLabel3.text")); // NOI18N
        jPanel.add(jLabel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PanelTematico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
