/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ej_final_gestion_heroes.gui;

import java.awt.Image;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author Robert
 */
public class FormularioAltaHeroes extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioAltaHeroes.class.getName());

    /**
     * Creates new form JDialogAddHeroes
     */
    public FormularioAltaHeroes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Locale.setDefault(new Locale("es", "ES"));
        initComponents();
        validaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombrePoder = new javax.swing.JLabel();
        jComboBoxPoder = new javax.swing.JComboBox<>();
        jLabelNombre2 = new javax.swing.JLabel();
        jDateChooserFechaAlta = new com.toedter.calendar.JDateChooser();
        jLabelFotoPoder = new javax.swing.JLabel();
        jButtonAddHeroeDialog = new javax.swing.JButton();
        jLabelNombrePoder1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNombre.setText(org.openide.util.NbBundle.getMessage(FormularioAltaHeroes.class, "FormularioAltaHeroes.jLabelNombre.text")); // NOI18N

        jTextFieldNombre.setText(org.openide.util.NbBundle.getMessage(FormularioAltaHeroes.class, "FormularioAltaHeroes.Nombre.text")); // NOI18N
        jTextFieldNombre.setName("Nombre"); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelNombrePoder.setText(org.openide.util.NbBundle.getMessage(FormularioAltaHeroes.class, "FormularioAltaHeroes.jLabelNombrePoder.text")); // NOI18N

        jComboBoxPoder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Volar", "Ser invisible", "Super fuerza", "Inmortal" }));
        jComboBoxPoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPoderActionPerformed(evt);
            }
        });

        jLabelNombre2.setText(org.openide.util.NbBundle.getMessage(FormularioAltaHeroes.class, "FormularioAltaHeroes.jLabelNombre2.text")); // NOI18N

        jLabelFotoPoder.setText(org.openide.util.NbBundle.getMessage(FormularioAltaHeroes.class, "FormularioAltaHeroes.jLabelFotoPoder.text")); // NOI18N

        jButtonAddHeroeDialog.setBackground(new java.awt.Color(0, 204, 51));
        jButtonAddHeroeDialog.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAddHeroeDialog.setText(org.openide.util.NbBundle.getMessage(FormularioAltaHeroes.class, "FormularioAltaHeroes.jButtonAddHeroeDialog.text")); // NOI18N
        jButtonAddHeroeDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddHeroeDialogActionPerformed(evt);
            }
        });

        jLabelNombrePoder1.setText(org.openide.util.NbBundle.getMessage(FormularioAltaHeroes.class, "FormularioAltaHeroes.jLabelNombrePoder1.text")); // NOI18N

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombre2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserFechaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombrePoder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombrePoder1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFotoPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddHeroeDialog)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombrePoder)
                    .addComponent(jComboBoxPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombrePoder1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombre2)
                    .addComponent(jDateChooserFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonAddHeroeDialog)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFotoPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(validationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonAddHeroeDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddHeroeDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddHeroeDialogActionPerformed

    private void jComboBoxPoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPoderActionPerformed
        String seleccion = (String) jComboBoxPoder.getSelectedItem();
        ImageIcon imagenOriginal;
        
        switch (seleccion.toLowerCase()) {
            case "volar":
                 imagenOriginal = new ImageIcon(getClass().getResource("/ej_final_gestion_heroes/imgs/volar.jpg"));
                break;
            case "ser invisible":
                 imagenOriginal = new ImageIcon(getClass().getResource("/ej_final_gestion_heroes/imgs/invisible.jpg"));
                 break;
            case "super fuerza":
                 imagenOriginal = new ImageIcon(getClass().getResource("/ej_final_gestion_heroes/imgs/fuerza.png"));
                 break;
            case "inmortal":
                 imagenOriginal = new ImageIcon(getClass().getResource("/ej_final_gestion_heroes/imgs/inmortal.jpg"));
                 break;
            default:
                throw new AssertionError();
        }
     
        // Ajustar escala
        Image img = imagenOriginal.getImage();
        Image scaledImg = img.getScaledInstance(jLabelFotoPoder.getWidth(), jLabelFotoPoder.getHeight(), java.awt.Image.SCALE_SMOOTH);

        // Asignar la imagen escalada
        jLabelFotoPoder.setIcon(new ImageIcon(scaledImg));
    }//GEN-LAST:event_jComboBoxPoderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioAltaHeroes dialog = new FormularioAltaHeroes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddHeroeDialog;
    private javax.swing.JComboBox<String> jComboBoxPoder;
    private com.toedter.calendar.JDateChooser jDateChooserFechaAlta;
    private javax.swing.JLabel jLabelFotoPoder;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombrePoder;
    private javax.swing.JLabel jLabelNombrePoder1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldNombre;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
    /**
     * Valida los datos del formulario
     */
    private void validaciones() {
        ValidationGroup group = validationPanel.getValidationGroup();

        group.add(jTextFieldNombre, StringValidators.REQUIRE_NON_EMPTY_STRING); // Que no deje vacío el string
        group.add(jTextFieldNombre, StringValidators.HOST_NAME); // Que sea un nombre

        validationPanel.addChangeListener((ChangeEvent e) -> {
            if (validationPanel.getProblem() == null) {
                jButtonAddHeroeDialog.setEnabled(true);
            } else {
                jButtonAddHeroeDialog.setEnabled(false);
            }
        });
    }
}
