/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_final_gestion_heroes.gui;

import ej_final_gestion_heroes.dto.Heroe;
import ej_final_gestion_heroes.logica.LogicaHeroes;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Robert
 */
public class GestorHeroes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestorHeroes.class.getName());
    private DefaultTableModel dtm;
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    /**
     * Creates new form GestorHeroes
     */
    public GestorHeroes() {
        Locale.setDefault(new Locale("es", "ES"));
        initComponents();
        mostrarLookAndFeel();
        cambiarIconoApp();
        mostrarFechayUnix();
        iniciarComponentesTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFecha = new javax.swing.JPanel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelUnix = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHeroes = new javax.swing.JTable();
        jPanelBotones = new javax.swing.JPanel();
        jButtonAddHeroe = new javax.swing.JButton();
        jButtonDeleteHeroe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTema = new javax.swing.JLabel();
        jComboLookAndFeel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFecha.setBackground(new java.awt.Color(0, 51, 102));
        jPanelFecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.lightGray, java.awt.Color.darkGray, new java.awt.Color(0, 204, 153)));
        jPanelFecha.setLayout(new java.awt.GridLayout(1, 0));

        jLabelFecha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText(org.openide.util.NbBundle.getMessage(GestorHeroes.class, "GestorHeroes.jLabelFecha.text")); // NOI18N
        jPanelFecha.add(jLabelFecha);

        jLabelUnix.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabelUnix.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUnix.setText(org.openide.util.NbBundle.getMessage(GestorHeroes.class, "GestorHeroes.jLabelUnix.text")); // NOI18N
        jPanelFecha.add(jLabelUnix);

        jTableHeroes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Poder", "Nivel", "Fecha de alta"
            }
        ));
        jScrollPane1.setViewportView(jTableHeroes);

        jPanelBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 0));

        jButtonAddHeroe.setBackground(new java.awt.Color(0, 153, 51));
        jButtonAddHeroe.setText(org.openide.util.NbBundle.getMessage(GestorHeroes.class, "GestorHeroes.jButtonAddHeroe.text")); // NOI18N
        jButtonAddHeroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddHeroeActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonAddHeroe);

        jButtonDeleteHeroe.setBackground(new java.awt.Color(153, 0, 0));
        jButtonDeleteHeroe.setText(org.openide.util.NbBundle.getMessage(GestorHeroes.class, "GestorHeroes.jButtonDeleteHeroe.text")); // NOI18N
        jButtonDeleteHeroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteHeroeActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonDeleteHeroe);

        jPanel1.setLayout(new java.awt.GridLayout());

        jLabelTema.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTema.setText(org.openide.util.NbBundle.getMessage(GestorHeroes.class, "GestorHeroes.jLabelTema.text")); // NOI18N
        jPanel1.add(jLabelTema);

        jComboLookAndFeel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLookAndFeelActionPerformed(evt);
            }
        });
        jPanel1.add(jComboLookAndFeel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(jPanelFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddHeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddHeroeActionPerformed
        FormularioAltaHeroes dialogHeroes = new FormularioAltaHeroes(this, true);
        dialogHeroes.setVisible(true);
        cargarDatosTabla();
    }//GEN-LAST:event_jButtonAddHeroeActionPerformed

    private void jButtonDeleteHeroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteHeroeActionPerformed
        eliminarHeroe();
    }//GEN-LAST:event_jButtonDeleteHeroeActionPerformed

    private void jComboLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLookAndFeelActionPerformed
        try {
            // Guarda el índice seleccionado
            UIManager.LookAndFeelInfo lookAndFeel = UIManager.getInstalledLookAndFeels()[jComboLookAndFeel.getSelectedIndex()];

            //  Con UIManager tenía un array con los Look And Feel instalados, entonces si accedo a la posición que 
            // me devuelve la línea anterior, obtendré el Look And Feel correspondiente 
            UIManager.setLookAndFeel(lookAndFeel.getClassName());

            // Refrescamos para que se apliquen los cambios, es decir, actualizamos todo el árbol de componentes del JFrame
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jComboLookAndFeelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestorHeroes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddHeroe;
    private javax.swing.JButton jButtonDeleteHeroe;
    private javax.swing.JComboBox<String> jComboLookAndFeel;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JLabel jLabelUnix;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHeroes;
    // End of variables declaration//GEN-END:variables
   /**
     * Muestra la fecha actual en "dd-MM-yyyy" y el tiempo en UNIX
     */
    private void mostrarFechayUnix() {
        // FECHA ACTUAL
        Date d = new Date();

        String fechaActual = sdf.format(d);
        jLabelFecha.setText(jLabelFecha.getText() + fechaActual);

        // HORA EN UNIX
        long timeStampSegundos = System.currentTimeMillis() / 1000;
        jLabelUnix.setText(jLabelUnix.getText() + timeStampSegundos + " seg");
    }

    /**
     * Cambia el icono de la app
     */
    private void cambiarIconoApp() {
        // Carga la imagen
        ImageIcon iconoApp = new ImageIcon(getClass().getResource("/ej_final_gestion_heroes/gui/imgs/icono.png"));

        // Asigna el objeto Image
        Image iconoImagen = iconoApp.getImage();

        // Lo asigna al icono del JFrame
        this.setIconImage(iconoImagen);
    }

    private void iniciarComponentesTabla() {
        // 1. INICIALIZAMOS DTM
        dtm = new DefaultTableModel();
        String[] titulos = new String[]{"Nombre", "Poder", "Nivel", "Fecha de alta"};
        dtm.setColumnIdentifiers(titulos);
        jTableHeroes.setModel(dtm); // Asignamos el modelo al JTable

        // 2. INICIALIZAMOS EL SORTER
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTableHeroes.getModel());
        jTableHeroes.setRowSorter(sorter);

        // Configurar orden inicial (Puntuación Descendente)
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        // Nivel de mayor a menor
        sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));
        // Fecha de alta de más reciente a menos
        sortKeys.add(new RowSorter.SortKey(3, SortOrder.DESCENDING));
        sorter.setSortKeys(sortKeys);

        // 3. Cargamos los datos iniciales
        cargarDatosTabla();
    }

    private void cargarDatosTabla() {
        // 1. Borrar todas las filas del modelo existente (dtm)
        dtm.setRowCount(0);

        // 2. Volver a llenar el modelo con los datos actualizados, y con la fecha formateada
        LogicaHeroes.getListaHeroes().forEach(h -> dtm.addRow(new Object[]{h.getNombre(), h.getPoder(), h.getNivel(), sdf.format(h.getFechaAlta())}));

        // 3. Forzar la reordenación
        RowSorter<? extends TableModel> sorter = jTableHeroes.getRowSorter();
        if (sorter != null) {
            // Usamos el cast al tipo concreto para acceder al método sort()
            ((TableRowSorter<?>) sorter).sort();
        }
    }

    /**
     * Elimina al héroe que requiera
     */
    private void eliminarHeroe() {
        // Si no hay ningún heróe registrado aún
        if (LogicaHeroes.getListaHeroes().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay héroes registrados aún", "No héroes", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Pide el nombre del héroe
        String heroeBorrar = JOptionPane.showInputDialog(this, "Introduce el héroe que quieres borrar", "Eliminar héroe", JOptionPane.QUESTION_MESSAGE);
        // Si ha cancelado la operación sale del panel
        if (heroeBorrar == null) {
            JOptionPane.showMessageDialog(this, "Operación cancelada", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (heroeBorrar.trim().isEmpty()) { // Si no ha introducido ningún nombre
            JOptionPane.showMessageDialog(this, "No has introducido ningún nombre", "NOMBRE HÉROE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Busca al héroe en la lista
        Heroe heroeBorrado = LogicaHeroes.getListaHeroes().stream()
                .filter(h -> h.getNombre()
                .equalsIgnoreCase(heroeBorrar))
                .findFirst().orElse(null);

        // Si no lo ha encontrado salta el error
        if (heroeBorrado == null) {
            JOptionPane.showMessageDialog(this, "ERROR. No existe el héroe " + heroeBorrar, "ERROR HÉROE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Pregunta de confirmación, si acepta lo borra definitivamente
        int decision = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas borrar el héroe " + heroeBorrado.getNombre() + "?",
                "¿Seguro?", JOptionPane.YES_NO_OPTION);
        if (decision == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Héroe eliminado con éxito", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
            LogicaHeroes.getListaHeroes().remove(heroeBorrado);
            cargarDatosTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Héroe no eliminado", "No eliminado", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * Muestra la info de los temas de la GUI
     */
    private void mostrarLookAndFeel() {
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();

        for (UIManager.LookAndFeelInfo lfi : UIManager.getInstalledLookAndFeels()) {
            dcm.addElement(lfi.getName());
        }

        jComboLookAndFeel.setModel(dcm);
    }
}
