/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_12_popup_multiple;

import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class PopUpMultiple extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PopUpMultiple.class.getName());

    /**
     * Creates new form PopUpMultiple
     */
    public PopUpMultiple() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPopUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPopUp.setBackground(new java.awt.Color(204, 204, 0));
        jButtonPopUp.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPopUp.setText(org.openide.util.NbBundle.getMessage(PopUpMultiple.class, "PopUpMultiple.jButtonPopUp.text")); // NOI18N
        jButtonPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPopUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButtonPopUp)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButtonPopUp)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPopUpActionPerformed
        popUpMultiple();
    }//GEN-LAST:event_jButtonPopUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PopUpMultiple().setVisible(true));
    }

    private void popUpMultiple() {
        int resultado = JOptionPane.showConfirmDialog(this, "¿Te gusta programar?", "Programación", JOptionPane.YES_NO_OPTION);

        if (resultado == JOptionPane.YES_OPTION) {
            String respuesta = JOptionPane.showInputDialog(this, "¿Cuál es tu lenguaje favorito?", "Favorito", JOptionPane.QUESTION_MESSAGE);
            if (respuesta == null) {
                JOptionPane.showMessageDialog(this, "No me canceles :(", "🙁", JOptionPane.INFORMATION_MESSAGE);
            } else if (respuesta.length() == 0) {
                JOptionPane.showMessageDialog(this, "No has elegido ninguno :(", "🙁", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (respuesta.equalsIgnoreCase("java")) {
                    JOptionPane.showMessageDialog(this, "Buena elección ;)", "😄", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Interesante...", "🤑", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } else {
            String respuesta2 = JOptionPane.showInputDialog(this, "¿Por qué no te gusta? :(", ":(", JOptionPane.QUESTION_MESSAGE);

            if (respuesta2 == null) {
                JOptionPane.showMessageDialog(this, "Parece que no quieres hablar conmigo :(", "🙁", JOptionPane.INFORMATION_MESSAGE);
            } else if (respuesta2.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Veo que no te gusta hablar tampoco...", "🙁", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Bueno, ya te gustará...", "😄", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPopUp;
    // End of variables declaration//GEN-END:variables
}
